name: Keep Render Alive

on:
  schedule:
    - cron: '*/14 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App
        run: |
          curl https://payflow-6wnc.onrender.com/health
          echo "Pinged successfully"
